// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUylk59-fd763cdCz060258d679j6cmyA',
    appId: '1:242908023765:web:03442f1af06cb924b54b5c',
    messagingSenderId: '242908023765',
    projectId: 'avandra-log-in',
    authDomain: 'avandra-log-in.firebaseapp.com',
    storageBucket: 'avandra-log-in.appspot.com',
    measurementId: 'G-XBQ21JKS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-ySzbbjdo3a1LJ9b47yMmJcaOl1gXcM',
    appId: '1:242908023765:android:519e85da6151bc39b54b5c',
    messagingSenderId: '242908023765',
    projectId: 'avandra-log-in',
    storageBucket: 'avandra-log-in.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Ca_00PabaqgdyPTnuoV5DPObuKyj2w',
    appId: '1:242908023765:ios:a25e9ef026482389b54b5c',
    messagingSenderId: '242908023765',
    projectId: 'avandra-log-in',
    storageBucket: 'avandra-log-in.appspot.com',
    iosClientId:
        '242908023765-elbj2vb7i10jl6j6oib5nt7403bjq3sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.avandra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Ca_00PabaqgdyPTnuoV5DPObuKyj2w',
    appId: '1:242908023765:ios:a25e9ef026482389b54b5c',
    messagingSenderId: '242908023765',
    projectId: 'avandra-log-in',
    storageBucket: 'avandra-log-in.appspot.com',
    iosClientId:
        '242908023765-elbj2vb7i10jl6j6oib5nt7403bjq3sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.avandra',
  );
}
